
name: Pipeline

on:
  push:
    branches: [ branch_graddlebuild ]
    
#starting buildjob
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2
        
      # Runs a single command using the runners shell 
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
                  
      - name: Step3 - Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          gradle-version: 4.10
          arguments: build
          
      - run: |
          ls '${{ github.workspace }}'
          ls '/home/runner/work/gs-spring-boot/'
          ls '/home/runner/work/'
          
      - name: Step5 Jfrog artifactory
        uses: jfrog/setup-jfrog-cli@v2.0.0
      #- run: jfrog rt ping --url https://www.google.co.in/
        
      - name: Step6 :sonarqube Scan code
        uses: vtex/action-sonarqube@main
        #with:
          #githubToken: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          #host: ${{ secrets.SQHost }} # Variable set in the Github Secrets
          #token: ${{ secrets.SQToken }} # Variable set in the Github Secrets
        
      - name: Step 7 - Deploy to CF
        uses: jhunt/cf-push@v1
        with:
          api: https://api.cf.ap21.hana.ondemand.com
          username: ramyaravindra999@gmail.com
          password: ${{ secrets.CF_PASSWORD }} #passing password through secrets
          org: 6fece677trial
          space: prod
          manifest: manifest.yml
